### ISSUE TITLE
So lately

### ISSUE THREAD

**Issue by fajarwahyu99** [badry-abderrahmane/medihelp#16] opened 2018-03-05 07:37 UTC
i have install this file.
and success. why loading for http://localhost/jarhelp/public/login so lately. 
this is screenshot
https://ibb.co/cHXZoS

Thanks you

**Comment by badry-abderrahmane** [comment] 2018-03-05 09:58
Please could you provide me more details on how did you install it ?
The steps you followed?

**Comment by fajarwahyu99** [comment] 2018-03-05 23:31
yes i followed your step for instal and running this program..

**Comment by fajarwahyu99** [comment] 2018-03-05 23:55
![gambar](https://user-images.githubusercontent.com/11350854/37006493-41b673d8-210b-11e8-828a-e365b56478be.png)

I try again but is the same problem. Load is very slow and not running program.

**Comment by fajarwahyu99** [comment] 2018-03-05 23:56
![gambar](https://user-images.githubusercontent.com/11350854/37006543-6f8b01ca-210b-11e8-99fc-42e9a8636f7e.png)

**Comment by badry-abderrahmane** [comment] 2018-03-06 09:35
Yes these are the needed steps. I want to ask you one more thing, Does the login page show at the end or it never shows up?

**Comment by badry-abderrahmane** [comment] 2018-03-06 09:37
Could you please send me a screen shot of the Chrome Devtools Console?

**Comment by fajarwahyu99** [comment] 2018-03-06 09:41
yes never show up..

**Comment by fajarwahyu99** [comment] 2018-03-06 09:41
wait , i will send you tomorrow

**Comment by fajarwahyu99** [comment] 2018-03-07 01:43
![image](https://user-images.githubusercontent.com/11350854/37068880-86238a78-21e3-11e8-8eed-07cbccd79392.png)

This is error

**Comment by badry-abderrahmane** [comment] 2018-03-07 10:02
Okey, I can see that the application does not find the needed ressources, And I think it's caused by your local Apache config so what you need to do is:

## Configuration for production

Go to your Apache virtual host configurations, I can see that you are using Xampp on Windows so the file will be located in : C:\xampp\apache\conf\extra\httpd-vhosts.conf .
You need to add these lines:


```
NameVirtualHost *:80
<VirtualHost *:80>
  DocumentRoot "C:/xampp/webdav/medihelp/public"
  ServerName 127.0.0.1
  ServerAlias 127.0.0.1
  <Directory  "C:/xampp/webdav/medihelp/public">
       Options +Indexes +FollowSymLinks +MultiViews
       AllowOverride All
       Allow from all
       Require all granted
   </Directory>
</VirtualHost>
```



You will need to change _C:/xampp/webdav/medihelp/public_ to your exact full path to public folder.

## Configuration for developpement

You need just to execute this command on application folder: `php artisan serv`
And then you can access it in the navigator: 127.0.0.1:8000

**Comment by badry-abderrahmane** [comment] 2018-03-07 10:05
You just need to choose one of the configurations and tell me if it works, so i would close the issue.

**Comment by fajarwahyu99** [comment] 2018-03-10 03:42
so, i can try php artisan serve?
okee i will try soon thank you

**Comment by fajarwahyu99** [comment] 2018-03-10 03:42
this is include SLA?

**Comment by badry-abderrahmane** [comment] 2018-03-10 08:58
What do you mean by SLA ?

**Comment by fajarwahyu99** [comment] 2018-03-11 23:51
![image](https://user-images.githubusercontent.com/11350854/37260100-c148deb4-25c1-11e8-9c8c-44a52cb997fb.png)

badri , i have open this. how i login or register?

**Comment by badry-abderrahmane** [comment] 2018-03-28 16:43
Sorry, I was on a vacation for the past two weeks. Please let me know if still have issues starting the application.
This is my skype ID: abderrahmane.badry

**Comment by fajarwahyu99** [comment] 2018-03-29 06:32
okee next monday i will contact you

**Closed as completed** 2018-04-15 17:21 UTC
